name: Deploy to FTP Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'

      - name: Install dependencies
        run: |
          npm ci --no-audit --prefer-offline
          npm install -g ftp-upload

      - name: Build project
        run: npm run build

      - name: Cleanup FTP folder
        uses: taylorgibb/ftp-clean@v2.0.3
        with:
          host: ${{ 'u99503wk.beget.tech' }}
          user: ${{ secrets.ART_FTP_USERNAME }}
          password: ${{ secrets.ART_FTP_PASSWORD }}
          exclude: '[".htaccess", ".htpasswd"]'

      - name: Upload to FTP server
        uses: sand4rt/ftp-deployer@v1.7
        with:
          sftp: false # optional
          host: ${{ 'u99503wk.beget.tech' }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          username: ${{ secrets.ART_FTP_USERNAME }} # FTP username
          password: ${{ secrets.ART_FTP_PASSWORD }} # FTP password
          cleanup: false # optional, remove existing files inside FTP remote folder
          passive: true # optional
